spring:
  datasource:
    url: jdbc:mysql://${db.host}:${db.port}/hcms_local
    username: ${db.username}
    password: ${db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

server:
  port: 8082

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

logging:
  config: classpath:logback-local.xml 