spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbcd
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  config: classpath:logback-local.xml 