spring:
  datasource:
    url: jdbc:mysql://15.207.207.149:3306/hcms-dev
    username: dev
    password: Root@123
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 443
  ssl:
    key-store-type: PKCS12
    key-store: /etc/letsencrypt/live/hcms-api.dev.technobevy.com/keystore.p12
    key-store-password: changeit
    key-alias: tomcat
logging:
  config: classpath:logback-dev.xml 