spring:
  datasource:
    url: jdbc:mysql://13.235.160.212:3306/myappdb
    username: myuser
    password: mypassword
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  config: classpath:logback-dev.xml 