spring:
  application:
    name: Health Care Management System
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://${db.host}:${db.port}/hcms_prod
    username: ${db.username}
    password: ${db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  jackson:
    time-zone: Asia/Kolkata

server:
  port: 8080
  forward-headers-strategy: framework

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    docExpansion: none
    enabled: true
    operationSorter: alpha
    tagsSorter: alpha
    displayRequestDuration: false
  api-docs:
    enabled: true
