name: Start EC2 Instance at 10 AM

on:
  schedule:
    - cron: '30 4 * * *'  # 10 AM IST (India is UTC+5:30)

jobs:
  start-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Start EC2 instance
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          inline-script: |
            aws ec2 start-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID }}
